const d3 = require('d3')
const _ = require('lodash')

module.exports = svg => {
    d3.select(svg)
        .selectAll('.hl')
        .data(_.range(0, 540, 20))
        .enter()
        .append('line')
        .attr('class', '.hl .grid')
        .attr('x1', '0px')
        .attr('x2', '2000px')
        .attr('y1', d => d)
        .attr('y2', d => d)
        .attr('stroke-width', '0.1px')
        .attr('stroke', '#777')
        .attr('stroke-dasharray', '0.3 0.3')
    d3.select(svg)
        .selectAll('.vl')
        .data(_.range(0, 1130, 20))
        .enter()
        .append('line')
        .attr('class', '.vl .grid')
        .attr('y1', '0px')
        .attr('y2', '2000px')
        .attr('x1', d => d)
        .attr('x2', d => d)
        .attr('stroke-width', '0.1px')
        .attr('stroke', '#777')
        .attr('stroke-dasharray', '0.3 0.3')
}
