---
title: "Fishing Condition"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plyr)
library(zoo)
library(ggplot2)
```

```{r}
#TYPE = "herring"
TYPE = "mackerel"
read_from <- function(path) {
  data = read.csv(path)
  yr_mean = ddply(data, .(year), summarize,  left=mean(left), scotland=mean(scotland), temperature=mean(temperature))
  yr_mean = yr_mean[yr_mean$year >= 2005, ]
  yr_mean
}

read_data <- function(path) {
  x1 = read_from(sprintf("../log_process/%s/result%s_1.csv", TYPE, path))
  x1$epoch = rep(1)
  x2 = read_from(sprintf("../log_process/%s/result%s_2.csv", TYPE, path))
  x2$epoch = rep(2)
  x3 = read_from(sprintf("../log_process/%s/result%s_3.csv", TYPE, path))
  x3$epoch = rep(3)
  
  x = rbind(x1, x2, x3)
  x = ddply(x, .(year), summarize,  left=mean(left), scotland=mean(scotland), temperature=mean(temperature))
  x$p_left = x$left / x$left[1]
  x$p_scotland = x$scotland / x$scotland[1]
  x
}

roll_mean_data <- function(data) {
  x = data.frame(rollmean(data, k=5))
  x$p_scotland = x$scotland / x$scotland[1]
  x$p_left = x$left / x$left[1]
  x
}

x1 = read_data("")
x2 = read_data("_0.05")
x3 = read_data("_0.02")
x1_ = roll_mean_data(x1)
x1_$case = rep("0.01 avg")
x2_ = roll_mean_data(x2)
x2_$case = rep("0.005 avg")
x3_ = roll_mean_data(x3)
x3_$case = rep("0.02 avg")
x1$Type = "orig"
x2$Type = "orig"
x3$Type = "orig"
x1_$Type = "avg"
x2_$Type = "avg"
x3_$Type = "avg"
x1$Size = 1
x2$Size = 1
x3$Size = 1
x1_$Size = 2
x2_$Size = 2
x3_$Size = 2
x1$Val = "0.01"
x2$Val = "0.005"
x3$Val = "0.02"
x1_$Val = "0.01"
x2_$Val = "0.005"
x3_$Val = "0.02"

x1$case = rep("0.01")
x2$case = rep("0.005")
x3$case = rep("0.02")
xx = rbind(x1, x2, x3, x1_, x2_, x3_)
xx$case = factor(xx$case)
xx

m_xx_old = xx
```

```{r}
ggplot(xx, aes(year, left, group = case)) + 
  geom_line(aes(linetype = Type, color = Val, size = Size)) +
  labs(y = "Proportion to First Year", x = "Year", color = "sigma\n") +
  scale_y_continuous(labels = scales::percent) +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(plot.margin = unit(c(0,0,0,0), "cm")) +
  scale_size(range=c(0.3, 1), guide=FALSE) +
  theme_minimal()
ggsave(sprintf('figure/case_%s_fish_total.pdf', TYPE), width=6, height=3)
```

```{r}
# pdf("figure/fish_yr.pdf", width=7, height=4) 
ggplot(xx, aes(year, scotland, group=case)) + 
  geom_line(aes(linetype = Type, color = Val, size = Size)) +
  labs(y = "Proportion to First Year", x = "Year", color = "sigma\n") +
  scale_y_continuous(labels = scales::percent) +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(plot.margin = unit(c(0,0,0,0), "cm")) +
  scale_size(range=c(0.3, 1), guide=FALSE) +
  theme_minimal()

ggsave(sprintf('figure/case_%s_fish_available.pdf', TYPE), width=6, height=3)

ggplot(xx, aes(year, scotland/left, group=case)) + 
  geom_line(aes(linetype = Type, color = Val, size = Size)) +
  labs(y = "Scotland / Total", x = "Year", color = "sigma\n") +
  scale_y_continuous(labels = scales::percent) +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(plot.margin = unit(c(0,0,0,0), "cm")) +
  scale_size(range=c(0.3, 1), guide=FALSE) +
  theme_minimal()

ggsave(sprintf('figure/case_%s_fish_ratio.pdf', TYPE), width=6, height=3)

```

```{r}
xx = h_xx
xx$scotland = h_xx$scotland * 0.3061 + m_xx$scotland * 0.6939
xx = xx[xx$Type == "avg", ]
ggplot(xx, aes(year, scotland, group=case)) + 
  geom_line(aes(color = Val, size = Size)) +
  labs(y = "Profit to First Year", x = "Year", color = "sigma\n") +
  scale_y_continuous(labels = scales::percent) +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(plot.margin = unit(c(0,0,0,0), "cm")) +
  scale_size(range=c(0.3, 1), guide=FALSE) +
  theme_minimal()

ggsave("figure/combined_fish.pdf", width=6, height=3)

```

```{r}
xxx = xx[xx$Type != "avg", ]
ggplot(xxx, aes(year, temperature, colour=case)) + 
  geom_line(linetype = "solid") +
  labs(y = "Temperature", x = "Year", color = "sigma\n") +
  geom_point() +
  theme(plot.margin = unit(c(0,0,0,0), "cm")) +
  
  theme(plot.title = element_text(hjust = 0.5)) +
  theme_minimal()
xxx
ggsave('figure/o_fish_temp.pdf', width=6, height=3)
```

```{r}
data$Type = rep("")
data[data$year>2019,]$Type = rep("Prediction")
data[data$year<=2019,]$Type = rep("History")
x = data[data$year_month=="2019-10",]
x$Type=rep("Prediction")
ndata = rbind(data, x)
xx = seq(100, 300, by=36)
ggplot(ndata[100:300,], aes(factor(id), temperature, group=1, colour=Type)) + 
  geom_line(linetype = "solid") +
  labs(y = "Temperature", x = "Year") +
  scale_x_discrete(breaks = xx, labels=ndata$year[xx]) +
  theme(plot.margin = unit(c(0,0,0,0), "cm")) +
  theme(plot.title = element_text(hjust = 0.5)) +
  
  theme_minimal()

ggsave('figure/fish_temp_month.pdf', width=6, height=4)
```