---
title: "distance_to_center"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
data = read.csv('./moving_or_not.csv')
data$dist = data$dist / 1000
```

```{r}
ggplot(data[data$fish == "Mackerel", ], aes(month, n / dist, color = type)) + 
  geom_line() +
  geom_point() +
  labs(y = "Count / Distance (km^-1)", x = "Month", linetype = "Location\n") +
  xlim(0, 13) +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(plot.margin = unit(c(0,0,0,0), "cm")) +
  theme_minimal()
ggsave('figure/distance_mackerel.pdf', width=6, height=3)

ggplot(data[data$fish == "Herring", ], aes(month, n / dist, color = type)) + 
  geom_line() +
  geom_point() +
  labs(y = "Count / Distance (km^-1)", x = "Month", linetype = "Location\n") +
  xlim(0, 13) +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(plot.margin = unit(c(0,0,0,0), "cm")) +
  theme_minimal()
ggsave('figure/distance_herring.pdf', width=6, height=3)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
