---
title: "Fishing Condition"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plyr)
library(zoo)
library(ggplot2)
```

```{r}
TYPE = "herring"
read_from <- function(path) {
  data = read.csv(path)
  yr_mean = ddply(data, .(year), summarize,  left=mean(left), scotland=mean(scotland), temperature=mean(temperature))
  yr_mean = yr_mean[yr_mean$year > 2004, ]
  yr_mean
}

read_data <- function(path) {
  x1 = read_from(sprintf("../log_process/%s/result%s_1.csv", TYPE, path))
  x1$epoch = rep(1)
  x2 = read_from(sprintf("../log_process/%s/result%s_2.csv", TYPE, path))
  x2$epoch = rep(2)
  x3 = read_from(sprintf("../log_process/%s/result%s_3.csv", TYPE, path))
  x3$epoch = rep(3)
  
  x = rbind(x1, x2, x3)
  x
}

read_data_roll_mean <- function(path) {
  x1 = data.frame(roll_mean_data(read_from(sprintf("../log_process/%s/result%s_1.csv", TYPE, path))))
  x1$epoch = rep(1)
  x2 = data.frame(roll_mean_data(read_from(sprintf("../log_process/%s/result%s_2.csv", TYPE, path))))
  x2$epoch = rep(2)
  x3 = data.frame(roll_mean_data(read_from(sprintf("../log_process/%s/result%s_3.csv", TYPE, path))))
  x3$epoch = rep(3)
  
  x = rbind(x1, x2, x3)
  x
}

roll_mean_data <- function(data) {
  x = rollmean(data, k=5)
}

#ndata.frame(roll_mean_data(x1))
x1 = read_data("")
x1_ = read_data_roll_mean("")
x1$Type = "orig"
x1_$Type = "avg"
x1$Size = 1
x1_$Size = 2
xx = rbind(x1, x1_)
xx$epoch = factor(xx$epoch)
xx
```

```{r}
ggplot(xx, aes(year, left)) + 
  geom_line(aes(linetype = Type, color = epoch, size = Size)) +
  labs(y = "Count", x = "Year", color="Epoch\n") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(plot.margin = unit(c(0,0,0,0), "cm")) +
  scale_size(range=c(0.3, 1), guide=FALSE) +
  theme_minimal()
ggsave(sprintf('figure/%s_fish_total.pdf', TYPE), width=6, height=3)
```

```{r}
# pdf("figure/fish_yr.pdf", width=7, height=4) 
ggplot(xx, aes(year, scotland)) + 
  geom_line(aes(linetype = Type, color = epoch, size = Size)) +
  labs(y = "Count", x = "Year", color = "Epoch\n") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(plot.margin = unit(c(0,0,0,0), "cm")) +
  scale_size(range=c(0.3, 1), guide=FALSE) +
  theme_minimal()

ggsave(sprintf('figure/%s_fish_available.pdf', TYPE), width=6, height=3)

ggplot(xx, aes(year, scotland/left)) + 
  geom_line(aes(linetype = Type, color = epoch, size = Size)) +
  labs(y = "Scotland / Total", x = "Year", color = "Epoch\n") +
  scale_y_continuous(labels = scales::percent) +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(plot.margin = unit(c(0,0,0,0), "cm")) +
  scale_size(range=c(0.3, 1), guide=FALSE) +
  theme_minimal()

ggsave(sprintf('figure/%s_fish_ratio.pdf', TYPE), width=6, height=3)

```

```{r}
xxx = xx[xx$Type != "avg", ]
ggplot(xxx, aes(year, temperature, colour=case)) + 
  geom_line(linetype = "solid") +
  labs(y = "Temperature", x = "Year", color = "sigma\n") +
  geom_point() +
  theme(plot.margin = unit(c(0,0,0,0), "cm")) +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme_minimal()
xxx
ggsave('figure/o_fish_temp.pdf', width=6, height=3)
```

```{r}
data$Type = rep("")
data[data$year>2019,]$Type = rep("Prediction")
data[data$year<=2019,]$Type = rep("History")
x = data[data$year_month=="2019-10",]
x$Type=rep("Prediction")
ndata = rbind(data, x)
xx = seq(100, 300, by=36)
ggplot(ndata[100:300,], aes(factor(id), temperature, group=1, colour=Type)) + 
  geom_line(linetype = "solid") +
  labs(y = "Temperature", x = "Year") +
  scale_x_discrete(breaks = xx, labels=ndata$year[xx]) +
  theme(plot.margin = unit(c(0,0,0,0), "cm")) +
  theme(plot.title = element_text(hjust = 0.5)) +
  
  theme_minimal()

ggsave('figure/fish_temp_month.pdf', width=6, height=4)
```