---
title: "Fishing Condition"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plyr)
library(ggplot2)
```

```{r}
data = read.csv("../log_process/mackerel/result_1.csv")
data2 = read.csv("../log_process/mackerel/result_2.csv")
data3 = read.csv("../log_process/mackerel/result_3.csv")

yr_mean = ddply(data, .(year), summarize,  left=mean(left), scotland=mean(scotland), temperature=mean(temperature))
yr_mean = yr_mean[yr_mean$year > 2003, ]
yr_mean$epoch = rep(1)
yr_mean_1 = ddply(data2, .(year), summarize,  left=mean(left), scotland=mean(scotland), temperature=mean(temperature))
yr_mean_1 = yr_mean_1[yr_mean_1$year > 2003, ]
yr_mean_1$epoch = rep(2)
yr_mean_2 = ddply(data3, .(year), summarize,  left=mean(left), scotland=mean(scotland), temperature=mean(temperature))
yr_mean_2 = yr_mean_2[yr_mean_2$year > 2003, ]
yr_mean_2$epoch = rep(3)
yr_mean = rbind(yr_mean, yr_mean_1, yr_mean_2)
yr_mean$epoch = factor(yr_mean$epoch)
#pdf("figure/fish_yr.pdf", width=7, height=4) 
# plot(left~year, yr_mean, type="o", xlab="Year", ylab="Count", main="Total Fish in Year")
#dev.off()
ggplot(yr_mean, aes(year, left, group=epoch, colour=epoch)) + 
  geom_line(linetype = "solid") +
  labs(y = "Count", x = "Year") +
  geom_point() +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(plot.margin = unit(c(0,0,0,0), "cm")) +
  theme_minimal()
ggsave('figure/fish_total.pdf', width=7, height=4)
```

```{r}
# pdf("figure/fish_yr.pdf", width=7, height=4) 
ggplot(yr_mean, aes(year, scotland, group=epoch, colour=epoch)) + 
  geom_line(linetype = "solid") +
  labs(y = "Count", x = "Year") +
  geom_point() +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(plot.margin = unit(c(0,0,0,0), "cm")) +
  theme_minimal()

ggsave('figure/fish_available.pdf', width=7, height=4)

ggplot(yr_mean, aes(year, scotland/left, group=epoch, colour=epoch)) + 
  geom_line(linetype = "solid") +
  labs(y = "Scotland / Total", x = "Year") +
  geom_point() +
  scale_y_continuous(labels = scales::percent) +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(plot.margin = unit(c(0,0,0,0), "cm")) +
  theme_minimal()

ggsave('figure/fish_ratio.pdf', width=7, height=4)

```

```{r}
yr_mean$Type = rep("")
yr_mean[yr_mean$year>2019,]$Type = rep("Prediction")
yr_mean[yr_mean$year<=2019,]$Type = rep("History")
x = yr_mean[yr_mean$year==2019,]
x$Type=rep("Prediction")
yr_mean = rbind(yr_mean, x)
ggplot(yr_mean, aes(year, temperature, colour=Type)) + 
  geom_line(linetype = "solid") +
  labs(y = "Temperature", x = "Year") +
  geom_point() +
  theme(plot.margin = unit(c(0,0,0,0), "cm")) +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme_minimal()

ggsave('figure/fish_temp.pdf', width=6, height=2)
```

```{r}
data$Type = rep("")
data[data$year>2019,]$Type = rep("Prediction")
data[data$year<=2019,]$Type = rep("History")
x = data[data$year_month=="2019-10",]
x$Type=rep("Prediction")
ndata = rbind(data, x)
xx = seq(100, 300, by=36)
ggplot(ndata[100:300,], aes(factor(id), temperature, group=1, colour=Type)) + 
  geom_line(linetype = "solid") +
  labs(y = "Temperature", x = "Year") +
  scale_x_discrete(breaks = xx, labels=ndata$year[xx]) +
  theme(plot.margin = unit(c(0,0,0,0), "cm")) +
  theme(plot.title = element_text(hjust = 0.5)) +
  
  theme_minimal()

ggsave('figure/fish_temp_month.pdf', width=6, height=2)
```